;NAME-Aman Kumar Singh
;REGD NO-2141019334
;EXPERIMENT 3 OBJ 1
;INTIALIZATION
MOV AX,0000H
MOV DS,AX
MOV SI,2000H
MOV CX,[SI]
MOV DX,0000H
MOV BX,CX
;ADDITION OF DATA
L2: INC SI
    INC SI
    ADD AX,[SI]
    JNC L1
    INC DX
    L1: DEC CX
    JNZ L2

    INC SI
    INC SI
    MOV [SI],AX ;RESULT OF SUM LOWER BYTES
    INC SI
    INC SI
    MOV [SI],DX ;RESULT OF SUM HIGHER BYTES
    
    DIV BX ;DX AND AX DIVIDED BY BX Q IN AX REM IN DX
    
    INC SI
    INC SI
    MOV [SI],AX
    INC SI
    INC SI
    MOV [SI],DX
    HLT